# Generated by Django 5.0.4 on 2024-04-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solde',
            field=models.IntegerField(default=5000),
        ),
    ]
