# Generated by Django 5.0.4 on 2024-04-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_solde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
