# Generated by Django 5.0.4 on 2024-04-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreFilm', models.CharField(max_length=300)),
                ('resume', models.TextField(max_length=2000)),
                ('nom_realisateur', models.CharField(max_length=300)),
                ('image_realisateur', models.ImageField(blank=True, null=True, upload_to='imgRealisateur/')),
                ('bande_annonce', models.CharField(blank=True, max_length=500, null=True)),
                ('langue', models.TextField(max_length=300)),
                ('categorie', models.TextField(max_length=300)),
                ('list_acteur', models.CharField(max_length=700)),
                ('equipage', models.CharField(max_length=700)),
                ('place_dispo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_match', models.CharField(max_length=300)),
                ('affiche_match', models.ImageField(blank=True, null=True, upload_to='imgAffiche_Match/')),
                ('categorie', models.TextField(max_length=300)),
                ('date_match', models.DateField()),
                ('heure_match', models.TimeField()),
                ('equipe_a', models.CharField(max_length=700)),
                ('logo_equipe_a', models.ImageField(upload_to='logoEquipeA')),
                ('logo_equipe_b', models.ImageField(upload_to='logoEquipeB')),
                ('equipe_b', models.CharField(max_length=700)),
                ('place_dispo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_places_reserves', models.IntegerField(default=0)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billeterie.film')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_places_reserves', models.IntegerField(default=0)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billeterie.sport')),
            ],
        ),
    ]
