# Generated by Django 5.0.4 on 2024-04-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('suject', models.TextField()),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='film',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation_film',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation_film',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation_film',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation_sport',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation_sport',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation_sport',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
