# Generated by Django 5.0.4 on 2024-04-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0002_contact_film_date_add_film_date_update_film_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imageFilm',
            field=models.ImageField(blank=True, null=True, upload_to='AfficheFilm/'),
        ),
    ]
