# Generated by Django 5.0.4 on 2024-04-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0003_film_imagefilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='lieu',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='prix_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='prix_three',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='prix_two',
            field=models.IntegerField(default=0),
        ),
    ]
