# Generated by Django 5.0.4 on 2024-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0004_film_prix_sport_description_sport_lieu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='dure_film',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
