# Generated by Django 5.0.4 on 2024-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0005_film_date_sortie_film_dure_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='resume',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
