# Generated by Django 5.0.4 on 2024-04-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0006_film_slug_alter_film_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='resume',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
