# Generated by Django 5.0.4 on 2024-04-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0007_alter_film_resume_alter_film_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
    ]
