# Generated by Django 5.0.4 on 2024-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0010_remove_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='lieu_cinema',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='resume',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
