# Generated by Django 5.0.4 on 2024-04-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0011_film_lieu_cinema_alter_film_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='lieu_cinema',
        ),
    ]
