# Generated by Django 5.0.4 on 2024-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0012_remove_film_lieu_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='lieu_cinema',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
