# Generated by Django 5.0.4 on 2024-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0013_film_lieu_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='debut_seance',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
