# Generated by Django 5.0.4 on 2024-04-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0015_reservation_film_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation_sport',
        ),
        migrations.DeleteModel(
            name='sport',
        ),
    ]
