# Generated by Django 5.0.4 on 2024-04-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0016_delete_reservation_sport_delete_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='suject',
            new_name='sujet',
        ),
    ]
